-- MySQL Script generated by MySQL Workbench
-- Fri Mar  8 09:21:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookstore` DEFAULT CHARACTER SET utf8 ;
USE `bookstore` ;

-- -----------------------------------------------------
-- Table `bookstore`.`book_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`book_language` (
  `id_lan` INT NOT NULL,
  `lan_code` VARCHAR(45) NOT NULL,
  `lan_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_lan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`publisher` (
  `pub_id` INT NOT NULL,
  `pub_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pub_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`book` (
  `book_id` INT NOT NULL,
  `b_title` VARCHAR(45) NOT NULL,
  `b_isbn` VARCHAR(45) NOT NULL,
  `b_pages` INT NOT NULL,
  `b_pubdate` DATE NOT NULL,
  `language_id` INT NOT NULL,
  `publisher_id` INT NOT NULL,
  PRIMARY KEY (`book_id`),
  INDEX `language_id_idx` (`language_id` ASC) VISIBLE,
  INDEX `publisher_id_idx` (`publisher_id` ASC) VISIBLE,
  CONSTRAINT `language_id`
    FOREIGN KEY (`language_id`)
    REFERENCES `bookstore`.`book_language` (`id_lan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `publisher_id`
    FOREIGN KEY (`publisher_id`)
    REFERENCES `bookstore`.`publisher` (`pub_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`author` (
  `auth_id` INT NOT NULL,
  `a_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`auth_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`book_author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`book_author` (
  `b_id` INT NOT NULL,
  `a_id` INT NOT NULL,
  PRIMARY KEY (`b_id`, `a_id`),
  INDEX `a_id_idx` (`a_id` ASC) VISIBLE,
  CONSTRAINT `b_id`
    FOREIGN KEY (`b_id`)
    REFERENCES `bookstore`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `a_id`
    FOREIGN KEY (`a_id`)
    REFERENCES `bookstore`.`author` (`auth_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`customer` (
  `c_id` INT NOT NULL,
  `c_firstname` VARCHAR(45) NOT NULL,
  `c_lastname` VARCHAR(45) NOT NULL,
  `c_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`c_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`shipping_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`shipping_method` (
  `method_id` INT NOT NULL,
  `m_name` VARCHAR(45) NOT NULL,
  `cost` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`method_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`country` (
  `id_country` INT NOT NULL,
  `country_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_country`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`address` (
  `add_id` INT NOT NULL,
  `street_number` VARCHAR(45) NOT NULL,
  `street_name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`add_id`),
  INDEX `country_id_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `country_id`
    FOREIGN KEY (`country_id`)
    REFERENCES `bookstore`.`country` (`id_country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`cust_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`cust_order` (
  `cor_id` INT NOT NULL,
  `order_date` DATETIME NOT NULL,
  `cust_id` INT NOT NULL,
  `shipping_metid` INT NOT NULL,
  `dest_address_id` INT NOT NULL,
  PRIMARY KEY (`cor_id`),
  INDEX `shipping_metid_idx` (`shipping_metid` ASC) VISIBLE,
  INDEX `cust_id_idx` (`cust_id` ASC) VISIBLE,
  INDEX `dest_address_id_idx` (`dest_address_id` ASC) VISIBLE,
  CONSTRAINT `shipping_metid`
    FOREIGN KEY (`shipping_metid`)
    REFERENCES `bookstore`.`shipping_method` (`method_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cust_id`
    FOREIGN KEY (`cust_id`)
    REFERENCES `bookstore`.`customer` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dest_address_id`
    FOREIGN KEY (`dest_address_id`)
    REFERENCES `bookstore`.`address` (`add_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`order_line`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`order_line` (
  `line_id` INT NOT NULL,
  `id_order` INT NOT NULL,
  `bk_id` INT NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`line_id`),
  INDEX `bk_id_idx` (`bk_id` ASC) VISIBLE,
  INDEX `order_id_idx` (`id_order` ASC) VISIBLE,
  CONSTRAINT `bk_id`
    FOREIGN KEY (`bk_id`)
    REFERENCES `bookstore`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_id`
    FOREIGN KEY (`id_order`)
    REFERENCES `bookstore`.`cust_order` (`cor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`order_status` (
  `s_id` INT NOT NULL,
  `st_value` VARCHAR(45) NULL,
  PRIMARY KEY (`s_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`order_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`order_history` (
  `history_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `status_id` INT NOT NULL,
  `status_date` DATE NOT NULL,
  PRIMARY KEY (`history_id`),
  INDEX `status_id_idx` (`status_id` ASC) VISIBLE,
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `status_id`
    FOREIGN KEY (`status_id`)
    REFERENCES `bookstore`.`order_status` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `bookstore`.`cust_order` (`cor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`address_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`address_status` (
  `id_status` INT NOT NULL,
  `address_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`customer_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`customer_address` (
  `customer_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `st_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `address_id`),
  INDEX `address_id_idx` (`address_id` ASC) VISIBLE,
  INDEX `st_id_idx` (`st_id` ASC) VISIBLE,
  CONSTRAINT `address_id`
    FOREIGN KEY (`address_id`)
    REFERENCES `bookstore`.`address` (`add_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `bookstore`.`customer` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `st_id`
    FOREIGN KEY (`st_id`)
    REFERENCES `bookstore`.`address_status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
