-- MySQL Script generated by MySQL Workbench
-- Fri Apr  4 10:30:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pharmastore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pharmastore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pharmastore` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pharmastore` ;

-- -----------------------------------------------------
-- Table `pharmastore`.`drugs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmastore`.`drugs` (
  `drugsid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `drugmanname` VARCHAR(155) NULL,
  `catname` VARCHAR(155) NULL,
  `buycost` DECIMAL(50,2) NULL,
  `sellprice` DECIMAL(50,2) NULL,
  `stock` INT NULL,
  PRIMARY KEY (`drugsid`))
ENGINE = InnoDB
AUTO_INCREMENT = 3093
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pharmastore`.`pharmacists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmastore`.`pharmacists` (
  `pharmid` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `postalcode` VARCHAR(45) NULL,
  `town` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`pharmid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pharmastore`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmastore`.`users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NULL,
  `lastname` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `phone` VARCHAR(255) NULL,
  `postalcode` VARCHAR(255) NULL,
  `town` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pharmastore`.`salesmen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmastore`.`salesmen` (
  `salesid` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NULL,
  `lastname` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `phonenum` VARCHAR(55) NULL,
  PRIMARY KEY (`salesid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pharmastore`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmastore`.`orders` (
  `orderid` INT NOT NULL AUTO_INCREMENT,
  `orderdate` DATETIME NULL,
  `ordstatus` VARCHAR(55) NULL,
  `ordquantity` INT NULL,
  `ordcost` DECIMAL(10,2) NULL,
  `userid` INT NOT NULL,
  `pharmasistid` INT NOT NULL,
  `salesmenid` INT NOT NULL,
  PRIMARY KEY (`orderid`, `userid`, `salesmenid`, `pharmasistid`),
  INDEX `userid_idx` (`userid` ASC) VISIBLE,
  INDEX `pharmsistsid_idx` (`pharmasistid` ASC) VISIBLE,
  INDEX `salesmenid_idx` (`salesmenid` ASC) VISIBLE,
  CONSTRAINT `pharmsistsid`
    FOREIGN KEY (`pharmasistid`)
    REFERENCES `pharmastore`.`pharmacists` (`pharmid`),
  CONSTRAINT `userid`
    FOREIGN KEY (`userid`)
    REFERENCES `pharmastore`.`users` (`ID`),
  CONSTRAINT `salesmenid`
    FOREIGN KEY (`salesmenid`)
    REFERENCES `pharmastore`.`salesmen` (`salesid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
KEY_BLOCK_SIZE = 2;


-- -----------------------------------------------------
-- Table `pharmastore`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmastore`.`order_items` (
  `id_order_item` INT NOT NULL AUTO_INCREMENT,
  `ordersid` INT NOT NULL,
  `drugid` INT NOT NULL,
  `quantity` INT NULL,
  `price` DECIMAL(50,2) NULL,
  `subtotal` DECIMAL(50,2) NULL,
  PRIMARY KEY (`id_order_item`, `ordersid`, `drugid`),
  INDEX `ordersid_idx` (`ordersid` ASC) VISIBLE,
  INDEX `drugid_idx` (`drugid` ASC) VISIBLE,
  CONSTRAINT `ordersid`
    FOREIGN KEY (`ordersid`)
    REFERENCES `pharmastore`.`orders` (`orderid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `drugid`
    FOREIGN KEY (`drugid`)
    REFERENCES `pharmastore`.`drugs` (`drugsid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
